/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulacionfrusa;

import java.awt.Graphics;
import java.awt.Graphics2D;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import static java.lang.System.out;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

//import static simulacionfrusa.RUSAcliente.port;
import static simulacionfrusa.datos.folio;


/**
 *
 * @author xavier
 */
public class panelImagen extends javax.swing.JPanel {

    BufferedImage img;
    double rotate_angle;
    double guardar;
    /**
     * Creates new form panelImagen
     */
    public panelImagen() {
        initComponents();
        img = null;
    }
     int i = 0;
    int j=0;

    
 
    public void paintComponent(Graphics g) {
        try {
            Thread.sleep(folio);
            
        Graphics2D g2d = (Graphics2D) (Graphics) g;
        g2d.translate(this.getSize().width / 2, this.getSize().height / 2);
        g2d.rotate(Math.toRadians(j--));
        updateUI();
        i++;
         
        //out.println("-" + Math.toRadians(i++));
      //  out.println("valor de Math.toRadianes:" + i*3.6);
         guardar=i*3.6;
          //port.setText(String.valueOf(guardar));
        try {
            g2d.drawImage(img, -img.getWidth() / 2, -img.getHeight() / 2, null);
              
            
        } catch (NullPointerException e) {
        }

        if (guardar >=360.0) {

               i=0;
             //  out.print("valor de i:"
               //        + i+"\n");
               
               
            }
        
//        if(guardar<3.7  && datos.numero_compara==0){
//            JOptionPane.showMessageDialog(null, "GANASTE:¡¡" +datos.nombre_cliente);
//          //  datos.numero_cliente=50000;
//        }else{
//          datos.numero_compara=-2;
//          // out.println("restablecer valor "+datos.numero_compara);
//        }
       
        } catch (InterruptedException ex) {
            Logger.getLogger(panelImagen.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    
    BufferedImage LoadImage(String Filename) {
        img = null;
        try {
            img = ImageIO.read(new File(Filename));
        } catch (IOException e) {
        }
           repaint();
        return img;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
