/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulacionfrusa;

import java.io.IOException;
import static java.lang.System.out;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author xavier
 */
public class RUSAservidor extends javax.swing.JFrame  implements Observer{

    private String nombreC;
    private String nombreP;
    private int puntuacionC;
    DefaultTableModel model = new DefaultTableModel();

    Servidor s = new Servidor(3128);

    /**
     * Creates new form RUSAservidor
     */
    public RUSAservidor() {
        initComponents();
        tablauser();
        update();
        
        

        s.addObserver(this);


    }

    void tablauser() {
        int i = 0;

        String[] Titulos = {"ID", "NOMBRE", "PUNTACION"};
        model.setColumnIdentifiers(Titulos);
        this.users.setModel(model);

        String[] d = new String[3];
        d[0] = "esperando..";
        d[1] = "esperando";
        d[2] = "esperando";
        model.addRow(d);

        users.setModel(model);

    }

    void mostrarUsurio(String id, String nombre, String puntuaje) {

    }

    void update() {

        model.addRow(new Object[]{"1", datos.Servidor_n, datos.Servidor_num});

    }

    /* Método filtro*/
    private void filtro(String consulta, JTable jtableBuscar) {
        model = (DefaultTableModel) jtableBuscar.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(model);
        jtableBuscar.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(consulta));
        out.println(tr.getViewRowCount());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actualizar = new javax.swing.JButton();
        iniciarS = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        users = new javax.swing.JTable();
        tcp = new javax.swing.JTextField();
        puerto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ip = new javax.swing.JLabel();
        port = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actualizar.setText("update");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        iniciarS.setBackground(new java.awt.Color(0, 153, 0));
        iniciarS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iniciarS.setText("INICIAR");
        iniciarS.setBorder(null);
        iniciarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSActionPerformed(evt);
            }
        });
        getContentPane().add(iniciarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 90, 30));

        users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(users);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 440, 330));

        tcp.setBackground(new java.awt.Color(204, 204, 255));
        tcp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tcp.setToolTipText("");
        tcp.setName(""); // NOI18N
        getContentPane().add(tcp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 210, 30));
        tcp.getAccessibleContext().setAccessibleName("");

        puerto.setBackground(new java.awt.Color(204, 204, 204));
        puerto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(puerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 110, 30));

        proceso.setColumns(20);
        proceso.setRows(5);
        jScrollPane2.setViewportView(proceso);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 290, 330));

        ip.setText("jLabel1");
        getContentPane().add(ip, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 200, 30));

        port.setText("jLabel2");
        getContentPane().add(port, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 110, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("IP DEL SERVIDOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 130, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 0));
        jLabel2.setText("PUERTO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 110, 30));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jButton2.setText("eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText("buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton1.setText("agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSActionPerformed

        Thread h = new Thread(s);
        h.start();


    }//GEN-LAST:event_iniciarSActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        model.setValueAt(tcp.getText(), users.getSelectedRow(), 0);
    }//GEN-LAST:event_actualizarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        model.removeRow(users.getSelectedRow());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //filtro("xavier",users);
        int fila = users.getRowCount();
        int i;
        String upd = "";
        String valor = "";
        int f = 0;
        int posicion = 0;
        for (i = 0; i < fila; i++) {
            f++;
            valor = (String) users.getValueAt(i, 1);
            if (valor.equals("xavier")) {
                //out.println("si esta" +valor);
                upd = valor;
                posicion = f;
                if (posicion >= 1) {
                    model.setValueAt(puerto.getText(), posicion - 1, 2);
                }

            } else {
                // out.println("no...");
            }
            //out.println( "valores de la columna1: " + valor);

        }
        //  posicion=posicion-1;
        // out.println("...."+upd+"posicion"+posicion);


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        update();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RUSAservidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RUSAservidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RUSAservidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RUSAservidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new RUSAservidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton iniciarS;
    private javax.swing.JLabel ip;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel port;
    public static final javax.swing.JTextArea proceso = new javax.swing.JTextArea();
    private javax.swing.JTextField puerto;
    private javax.swing.JTextField tcp;
    private javax.swing.JTable users;
    // End of variables declaration//GEN-END:variables

        @Override
    public void update(Observable o, Object arg) {

        if (arg instanceof String) {
           nombreP = (String) arg;           
            
        }else{
            int valor = (int) arg;
            model.addRow(new Object[]{"1", nombreP,valor});
            
            }
            
        }

    }

