/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulacionfrusa;

import java.awt.Color;
import static java.lang.System.out;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author xavier
 */
public class RUSAcliente extends javax.swing.JFrame {

    String seguir;
    int numero = 0;
    Cliente cliente = new Cliente("192.168.0.10", 3128);

    /**
     * Creates new form RUSAservidor
     */
    busqueda t = new busqueda();

    public RUSAcliente() {
        initComponents();
        //establecer imagen dentro del panel
        panelImagen1.LoadImage("src\\imagenes\\folder\\g2.jpg");

        colores();
        //t.start();//busqueda hilo 

    }

    void colores() {

        uno.setBackground(Color.red);
        dos.setBackground(Color.black);
        tres.setBackground(Color.red);

        cuatro.setBackground(Color.black);

        cinco.setBackground(Color.red);
        seis.setBackground(Color.black);

        siete.setBackground(Color.red);

        ocho.setBackground(Color.black);

        nueve.setBackground(Color.red);

        dies.setBackground(Color.black);

        once.setBackground(Color.red);

        doce.setBackground(Color.black);

        trece.setBackground(Color.red);

        catorce.setBackground(Color.black);

        quince.setBackground(Color.red);

        diciseis.setBackground(Color.black);

        diecisiete.setBackground(Color.red);

        diciocho.setBackground(Color.black);

        dicinueve.setBackground(Color.red);

        veinte.setBackground(Color.black);

        veintiuno.setBackground(Color.red);

        veintidos.setBackground(Color.black);

        veintitres.setBackground(Color.red);

        veinticuatro.setBackground(Color.black);

        veinticinco.setBackground(Color.red);

        veintiseis.setBackground(Color.black);

        veintisiete.setBackground(Color.red);

        veintiocho.setBackground(Color.black);

        veintinueve.setBackground(Color.red);

        treinta.setBackground(Color.black);

        treintauno.setBackground(Color.red);

        treintados.setBackground(Color.black);

        treintatres.setBackground(Color.red);

        treintacuatro.setBackground(Color.black);

        treintacinco.setBackground(Color.red);

        treintaseis.setBackground(Color.black);

    }

    void num() {
        
        int max = 10;
        int min = 1;
        int range = max - min + 1;

        // generate random numbers within 1 to 10 
        //for (int i = 0; i < 1; i++) {
        int rand = (int) (Math.random() * range) + min;
        rojo.setText(String.valueOf(rand));
        datos.numero_compara = rand;
        t.random();//busca para poner en verde el numero que sale junto con el random
        if (rand == datos.numero_cliente) {
            JOptionPane.showMessageDialog(null, "Ganaste");
             try {
            Thread.sleep(10000);
            //  t.reiniciar(); busqueda
            colores();
            datos.b = false;
        } catch (InterruptedException ex) {
            Logger.getLogger(RUSAcliente.class.getName()).log(Level.SEVERE, null, ex);
        }



        } else {
            
            JOptionPane.showMessageDialog(null, "Perdiste\n" + datos.nombre_cliente);
             try {
            Thread.sleep(10000);
            //  t.reiniciar(); busqueda
            colores();
            datos.b = false;
        } catch (InterruptedException ex) {
            Logger.getLogger(RUSAcliente.class.getName()).log(Level.SEVERE, null, ex);
        }


           

        }
        // Output is different everytime this code is executed 
        //   System.out.println(rand);
        //}

    }

    inicio() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        conec = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        puntuaje = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelImagen1 = new simulacionfrusa.panelImagen();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        elejido = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        conec.setBackground(new java.awt.Color(153, 255, 153));
        conec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        conec.setText("PARAR");
        conec.setBorder(null);
        conec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conecActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOMBRE:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PUNTUACION:");

        puntuaje.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        puntuaje.setForeground(new java.awt.Color(255, 255, 255));

        nombre.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelImagen1Layout = new javax.swing.GroupLayout(panelImagen1);
        panelImagen1.setLayout(panelImagen1Layout);
        panelImagen1Layout.setHorizontalGroup(
            panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        panelImagen1Layout.setVerticalGroup(
            panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/folder/flecha.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        jPanel3.setBackground(new java.awt.Color(0, 51, 0));
        jPanel3.setForeground(new java.awt.Color(153, 0, 0));

        nueve.setText("9");

        doce.setText("12");

        quince.setText("15");

        diciocho.setText("18");

        veintiuno.setText("21");

        treintatres.setText("33");

        treintaseis.setText("36");

        seis.setText("6");

        tres.setText("3");

        veinticuatro.setText("24");

        veintisiete.setText("27");

        treinta.setText("30");

        dos.setText("2");

        cinco.setText("5");

        ocho.setText("8");

        once.setText("11");

        catorce.setText("14");

        diecisiete.setText("17");

        veinte.setText("20");

        veintitres.setText("23");

        veintiseis.setText("26");

        veintinueve.setText("29");

        treintados.setText("32");

        treintacinco.setText("35");

        treintauno.setText("31");

        treintacuatro.setText("34");

        veintiocho.setText("28");

        veinticinco.setText("25");

        veintidos.setText("22");

        dicinueve.setText("19");

        diciseis.setText("16");

        trece.setText("13");

        dies.setText("10");

        siete.setText("7");

        cuatro.setText("4");

        uno.setText("1");

        jLabel5.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/folder/monedas.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(dos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cinco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ocho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(once)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(catorce)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diecisiete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veinte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veintitres)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veintiseis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veintinueve))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(uno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cuatro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(siete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dies)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(trece)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diciseis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dicinueve)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veintidos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veinticinco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veintiocho)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(treintauno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(treintacuatro))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(treintados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(treintacinco))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tres)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nueve)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doce)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quince)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diciocho)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(veintiuno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(veinticuatro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(veintisiete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(treinta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(treintatres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(treintaseis))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(80, 80, 80))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addGap(131, 131, 131)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nueve)
                    .addComponent(doce)
                    .addComponent(quince)
                    .addComponent(diciocho)
                    .addComponent(veintiuno)
                    .addComponent(treintatres)
                    .addComponent(treintaseis)
                    .addComponent(seis)
                    .addComponent(tres)
                    .addComponent(veinticuatro)
                    .addComponent(veintisiete)
                    .addComponent(treinta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dos)
                    .addComponent(cinco)
                    .addComponent(ocho)
                    .addComponent(once)
                    .addComponent(catorce)
                    .addComponent(diecisiete)
                    .addComponent(veinte)
                    .addComponent(veintitres)
                    .addComponent(veintiseis)
                    .addComponent(veintinueve)
                    .addComponent(treintados)
                    .addComponent(treintacinco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(treintauno)
                    .addComponent(treintacuatro)
                    .addComponent(veintiocho)
                    .addComponent(veinticinco)
                    .addComponent(veintidos)
                    .addComponent(dicinueve)
                    .addComponent(diciseis)
                    .addComponent(trece)
                    .addComponent(dies)
                    .addComponent(siete)
                    .addComponent(cuatro)
                    .addComponent(uno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(46, 46, 46))
        );

        rojo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rojo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(panelImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(panelImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NUMERO:");

        elejido.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        elejido.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("COMO JUGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(conec, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puntuaje, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elejido, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(29, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(puntuaje, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(elejido, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButton1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(conec, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void conecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conecActionPerformed
        Thread h = new Thread(cliente);//coneccion al servidor
        h.start();
        num();//numero random
       
    }//GEN-LAST:event_conecActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Bienvenido");
        JOptionPane.showInputDialog(null, "1.DEBES ELEGIR UN NUMERO DE LA RULETA [1 AL 36]\n2.INGRESA LA CANTIDAD QUE DESEAS APOSTAR\n3.SI GANAS SE DUPLICA TUCREDITO", "Informacion", JOptionPane.INFORMATION_MESSAGE)
        );
        datos.nombre_cliente = String.valueOf(JOptionPane.showInputDialog(null, "Ingresa tu nombre", "Datos", JOptionPane.INFORMATION_MESSAGE));
        nombre.setText(datos.nombre_cliente);
        datos.numero_cliente = Integer.parseInt(JOptionPane.showInputDialog(null, datos.nombre_cliente + "\nIngresa un numero!", ":)", JOptionPane.INFORMATION_MESSAGE));
        datos.cantidad_cliente = Integer.parseInt(JOptionPane.showInputDialog(null, datos.nombre_cliente + "\n¿Quecantidad deseas apostar?", ":)", JOptionPane.INFORMATION_MESSAGE));
        puntuaje.setText(String.valueOf(datos.cantidad_cliente));
        elejido.setText(String.valueOf(datos.numero_cliente));


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RUSAcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RUSAcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RUSAcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RUSAcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RUSAcliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JButton catorce = new javax.swing.JButton();
    public static final javax.swing.JButton cinco = new javax.swing.JButton();
    private javax.swing.JButton conec;
    public static final javax.swing.JButton cuatro = new javax.swing.JButton();
    public static final javax.swing.JButton dicinueve = new javax.swing.JButton();
    public static final javax.swing.JButton diciocho = new javax.swing.JButton();
    public static final javax.swing.JButton diciseis = new javax.swing.JButton();
    public static final javax.swing.JButton diecisiete = new javax.swing.JButton();
    public static final javax.swing.JButton dies = new javax.swing.JButton();
    public static final javax.swing.JButton doce = new javax.swing.JButton();
    public static final javax.swing.JButton dos = new javax.swing.JButton();
    private javax.swing.JLabel elejido;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nombre;
    public static final javax.swing.JButton nueve = new javax.swing.JButton();
    public static final javax.swing.JButton ocho = new javax.swing.JButton();
    public static final javax.swing.JButton once = new javax.swing.JButton();
    private simulacionfrusa.panelImagen panelImagen1;
    private javax.swing.JLabel puntuaje;
    public static final javax.swing.JButton quince = new javax.swing.JButton();
    public static final javax.swing.JLabel rojo = new javax.swing.JLabel();
    public static final javax.swing.JButton seis = new javax.swing.JButton();
    public static final javax.swing.JButton siete = new javax.swing.JButton();
    public static final javax.swing.JButton trece = new javax.swing.JButton();
    public static final javax.swing.JButton treinta = new javax.swing.JButton();
    public static final javax.swing.JButton treintacinco = new javax.swing.JButton();
    public static final javax.swing.JButton treintacuatro = new javax.swing.JButton();
    public static final javax.swing.JButton treintados = new javax.swing.JButton();
    public static final javax.swing.JButton treintaseis = new javax.swing.JButton();
    public static final javax.swing.JButton treintatres = new javax.swing.JButton();
    public static final javax.swing.JButton treintauno = new javax.swing.JButton();
    public static final javax.swing.JButton tres = new javax.swing.JButton();
    public static final javax.swing.JButton uno = new javax.swing.JButton();
    public static final javax.swing.JButton veinte = new javax.swing.JButton();
    public static final javax.swing.JButton veinticinco = new javax.swing.JButton();
    public static final javax.swing.JButton veinticuatro = new javax.swing.JButton();
    public static final javax.swing.JButton veintidos = new javax.swing.JButton();
    public static final javax.swing.JButton veintinueve = new javax.swing.JButton();
    public static final javax.swing.JButton veintiocho = new javax.swing.JButton();
    public static final javax.swing.JButton veintiseis = new javax.swing.JButton();
    public static final javax.swing.JButton veintisiete = new javax.swing.JButton();
    public static final javax.swing.JButton veintitres = new javax.swing.JButton();
    public static final javax.swing.JButton veintiuno = new javax.swing.JButton();
    // End of variables declaration//GEN-END:variables

}

                                                                                   
